# Generated by Django 4.1.3 on 2022-12-19 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modadlidade', models.CharField(choices=[('INT', 'Integrado'), ('SUB', 'Subsequente'), ('CON', 'Concomitante')], max_length=3)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.departamento')),
            ],
        ),
    ]
