# Generated by Django 4.1.3 on 2022-12-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='modadlidade',
            new_name='modalidade',
        ),
    ]
