# Generated by Django 4.1.4 on 2022-12-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('1', 'Cachorro'), ('2', 'Gato')], max_length=10, null=True),
        ),
    ]
