# Generated by Django 4.1.4 on 2022-12-30 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_consultaveterinaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('crmv', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.animal'),
        ),
    ]
