# Generated by Django 4.1.4 on 2022-12-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_veterinario_alter_consultaveterinaria_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.animal'),
        ),
    ]
