# Generated by Django 4.1.4 on 2022-12-30 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_alter_consultaveterinaria_animal'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultaveterinaria',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.veterinario'),
        ),
    ]
